// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWbxIJtZo296oBrMvvGX5kP2_I4-BU7O0',
    appId: '1:1031710300824:web:88e2aa383197c476f68eed',
    messagingSenderId: '1031710300824',
    projectId: 'sweetrush-32888',
    authDomain: 'sweetrush-32888.firebaseapp.com',
    storageBucket: 'sweetrush-32888.firebasestorage.app',
    measurementId: 'G-FDNB3NQNKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47yg8OOqwfIdPFl-7jQ7FroDKzBKumdQ',
    appId: '1:1031710300824:android:d2c64d2316ccf070f68eed',
    messagingSenderId: '1031710300824',
    projectId: 'sweetrush-32888',
    storageBucket: 'sweetrush-32888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHN5n9gbsN1eJZROxQA3e_hnyK4u87jc',
    appId: '1:1031710300824:ios:7927b80f5418b667f68eed',
    messagingSenderId: '1031710300824',
    projectId: 'sweetrush-32888',
    storageBucket: 'sweetrush-32888.firebasestorage.app',
    iosBundleId: 'com.example.sweetrush',
  );
}
